# K nearest classifier

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

C:\Users\mdaza\AppData\Local\Temp\ipykernel_15448\555797462.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


# make_classification

***from sklearn.datasets import make_classification***

In [3]:
from sklearn.datasets import make_classification

X , y = make_classification(n_samples=1000  , n_features=3, n_redundant=0, n_classes=2, random_state=2)

In [4]:
X , y

(array([[-1.30758298, -1.47755921,  0.00762306],
        [-0.80640285, -0.71836268, -0.40312064],
        [-0.20302542, -0.89439288,  0.22550145],
        ...,
        [ 0.80182862, -0.25997723,  1.31953137],
        [ 1.58130685,  0.37186148, -0.74981404],
        [-1.18091239, -1.28568141,  0.67276212]]),
 array([0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
        0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
        1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
        1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
        0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
        0, 1, 1, 1, 1, 0,

In [5]:
X.shape

(1000, 3)

# train_test_split

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.2 , random_state=5)

In [8]:
X_train.shape , X_test.shape

((800, 3), (200, 3))

# KNeighborsClassifier

***from sklearn.neighbors import KNeighborsClassifier***

In [11]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model

KNeighborsClassifier()

In [12]:
model.fit(X_train, y_train)

KNeighborsClassifier()

***model predict***

In [14]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1])

***from sklearn.metrics import accuracy_score , confusion_matrix , classification_report***

In [15]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [18]:
print(accuracy_score(y_pred , y_test)*100)

print(confusion_matrix(y_pred , y_test))

print(classification_report(y_pred , y_test))

89.5
[[100  11]
 [ 10  79]]
              precision    recall  f1-score   support

           0       0.91      0.90      0.90       111
           1       0.88      0.89      0.88        89

    accuracy                           0.90       200
   macro avg       0.89      0.89      0.89       200
weighted avg       0.90      0.90      0.90       200



# Hyperparameter Tuning

***hyperparameter tuning on KNeighborsClassifier***

In [32]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski']
}

model_name = KNeighborsClassifier()

In [33]:

GridSearch = GridSearchCV(estimator = model_name,
             param_grid = param_grid,
             scoring = 'roc_auc',
             cv = 5)

In [36]:
GridSearch.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']},
             scoring='roc_auc')

In [37]:
GridSearch.best_params_

{'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'distance'}

In [46]:
GridSearch.best_score_*100

93.87567006688133

In [40]:
GridSearch.best_estimator_

KNeighborsClassifier(metric='manhattan', n_neighbors=11, weights='distance')

In [43]:
y_best_pred = GridSearch.predict(X_test)
y_best_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1])

In [42]:
from sklearn.metrics import accuracy_score , confusion_matrix , classification_report

In [44]:
print(accuracy_score(y_best_pred , y_test)*100)

print(confusion_matrix(y_best_pred , y_test))

print(classification_report(y_best_pred , y_test))

88.5
[[101  14]
 [  9  76]]
              precision    recall  f1-score   support

           0       0.92      0.88      0.90       115
           1       0.84      0.89      0.87        85

    accuracy                           0.89       200
   macro avg       0.88      0.89      0.88       200
weighted avg       0.89      0.89      0.89       200

