# K nearest regressor

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
from sklearn.datasets import make_regression

X , y = make_regression(n_samples=1000, n_features=2, noise = 3, random_state=1)

In [4]:
X , y

(array([[-0.91542437, -1.94504696],
        [-2.30490794, -0.59246129],
        [-0.43750898, -0.78191168],
        ...,
        [-0.46867382,  0.02186284],
        [-0.44265541,  0.55753264],
        [-0.13971173,  0.85328219]]),
 array([-190.03258306,  -85.26051217,  -79.38260295,  -68.46860406,
           7.6776908 ,  -40.35627711,   37.76165512,  -98.68667297,
        -103.49936616, -111.4844082 ,   74.447244  ,   16.74943836,
        -113.89842347,  127.60069439, -104.93211336,   46.33988172,
          14.22936786,  -67.02417655, -110.81141065, -148.68676949,
           8.82971657,   15.87695178,  -14.63414628,   72.69620209,
         108.28395145,    4.7681583 ,  122.70577279,   26.80503947,
          26.05435416,  -22.0578647 ,   76.52458928, -259.93124079,
          26.45161346,  -43.02760158,   31.73017335,  -41.68557901,
          20.2425586 ,  -38.08420722,  -27.93409336,   94.98962026,
          52.38050255,   94.41735191,   27.21304024,  -40.32774788,
         -42.33719649

In [5]:
X.shape

(1000, 2)

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X , y , test_size=0.2 , random_state=5)

In [7]:
X_train.shape , X_test.shape

((800, 2), (200, 2))

In [10]:
from sklearn.neighbors import KNeighborsRegressor

model = KNeighborsRegressor()
model

KNeighborsRegressor()

In [13]:
model.fit(X_train , y_train)

KNeighborsRegressor()

In [15]:
y_pred = model.predict(X_test)
y_pred

array([  51.05526972,   77.98952007,   86.1401422 ,   16.48999243,
        -44.35553801,  -18.94611338, -110.58236797,   20.80640223,
         93.43640791,  107.40161179,    2.08739441,  127.70160236,
        151.91683254,  -12.80304503,  -27.38811422,  -62.93270087,
       -107.48441905,  -55.36492016,   22.82408021,  -23.32819209,
        139.88665309,   45.84071466,   -8.87275579, -112.58475226,
         43.75213757,  -91.32686644,  -62.22137879, -186.13790767,
         22.07523521,  -85.4951278 ,   27.20788212,   23.53642157,
       -178.71223171,   48.37072792,  -52.94648118,   96.89660743,
       -112.15193316,   31.5633561 , -140.19451922, -162.26363198,
         47.22108464,   14.05223334,  -80.15531977,  -89.18591701,
        -72.93205844,  130.78569202,    3.89713083, -192.67924714,
         -4.5827389 ,  -90.18223463,   70.59927014, -194.77105166,
        -39.34887956,  -84.29666438,   27.95364115,  -75.80247444,
        126.53362605,  125.73947087,  -56.32181554, -133.60795

# r2_score

***from sklearn.metrics import r2_score***

In [17]:
from sklearn.metrics import r2_score

r2_score(y_test , y_pred)*100

98.94561153577077

# Hyperparameter Tuning

***hyperparameter tuning on KNeighborsRegressor***

In [18]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import GridSearchCV

model_name = KNeighborsRegressor()

# Define the parameter grid
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski']
}

In [19]:
GridSearch = GridSearchCV(estimator=model_name , param_grid=param_grid, cv=5, verbose=1)

In [20]:
GridSearch.fit(X_train , y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits


GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'metric': ['euclidean', 'manhattan', 'minkowski'],
                         'n_neighbors': [3, 5, 7, 9, 11],
                         'weights': ['uniform', 'distance']},
             verbose=1)

In [21]:
GridSearch.best_params_

{'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'distance'}

In [23]:
GridSearch.best_score_*100

99.0072547950779

In [26]:
best_model = GridSearch.best_estimator_
best_model

KNeighborsRegressor(metric='manhattan', n_neighbors=3, weights='distance')

In [28]:
y_best_pred = best_model.predict(X_test)
y_best_pred

array([ 4.97664112e+01,  8.12091281e+01,  8.77655084e+01,  1.52990239e+01,
       -4.18120752e+01, -1.66778151e+01, -1.08428610e+02,  1.77599880e+01,
        9.08489487e+01,  1.06260726e+02, -9.10183249e-03,  1.35461704e+02,
        1.51876814e+02, -1.32191813e+01, -2.70775494e+01, -5.96010330e+01,
       -1.10865038e+02, -5.28527104e+01,  2.47020765e+01, -2.62226429e+01,
        1.29881474e+02,  5.14947816e+01, -9.92318992e+00, -1.09826510e+02,
        4.27551328e+01, -8.87546838e+01, -6.41267420e+01, -1.85296017e+02,
        2.08898179e+01, -8.81745989e+01,  2.82771500e+01,  1.60387375e+01,
       -1.75058235e+02,  5.04570985e+01, -5.46925332e+01,  9.46384633e+01,
       -1.13209089e+02,  4.56139974e+01, -1.48874853e+02, -1.46347510e+02,
        4.61690025e+01,  1.41812273e+01, -7.58423297e+01, -8.51924594e+01,
       -7.16248442e+01,  1.36329019e+02, -2.13285388e+00, -1.74819379e+02,
       -3.96213986e+00, -9.27249314e+01,  7.22043162e+01, -1.92150267e+02,
       -3.06328483e+01, -

In [30]:
from sklearn.metrics import r2_score

r2_score(y_test , y_best_pred)*100

99.14239388551394