# XGboost implementation

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib as plt

C:\Users\mdaza\AppData\Local\Temp\ipykernel_23716\1945047112.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [2]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
from xgboost import XGBRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [4]:
X , y  = make_regression(n_samples = 1000 , n_features = 2 , noise=10 , random_state = 1)

In [5]:
X,y

(array([[-0.91542437, -1.94504696],
        [-2.30490794, -0.59246129],
        [-0.43750898, -0.78191168],
        ...,
        [-0.46867382,  0.02186284],
        [-0.44265541,  0.55753264],
        [-0.13971173,  0.85328219]]),
 array([-1.98367142e+02, -7.18777056e+01, -8.69703239e+01, -6.96492401e+01,
         1.82745760e+01, -3.77114686e+01,  3.92726728e+01, -9.78831863e+01,
        -9.79418533e+01, -1.18326213e+02,  7.37176065e+01,  1.15947984e+01,
        -1.14639116e+02,  1.18554758e+02, -1.09479268e+02,  4.55822523e+01,
         1.22163385e+01, -7.55247901e+01, -1.07584299e+02, -1.52546032e+02,
         6.76376929e+00,  9.63814831e+00, -2.16279129e+01,  7.04567440e+01,
         1.07700199e+02,  1.09477518e+01,  1.17165036e+02,  2.78449353e+01,
         3.24248766e+01, -1.55808165e+01,  9.64321593e+01, -2.68980403e+02,
         3.04398725e+01, -5.03731238e+01,  1.83865434e+01, -4.20020243e+01,
         2.60722898e+01, -4.24419694e+01, -2.84245422e+01,  7.87732991e+01,
         

In [6]:
X_train , X_test, y_train, y_test = train_test_split(X , y , test_size = 0.2)

In [7]:
Regressor = XGBRegressor()

In [8]:
Regressor.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [9]:
y_pred = Regressor.predict(X_test)
y_pred

array([-4.80569506e+00, -1.56765900e+02,  8.39452076e+00, -2.19618973e+02,
        1.05187988e+02,  1.46625885e+02, -2.67049847e+01, -5.91916122e+01,
       -1.62279167e+01,  9.23387718e+00,  1.09489107e+01,  5.29770622e+01,
       -2.54912853e+01, -2.43668537e+01, -7.85827413e-02, -4.38701820e+01,
        3.56558800e-01, -2.08421356e+02, -8.07635021e+00, -1.34564829e+01,
       -5.77157745e+01,  2.35740399e+00,  7.45376129e+01, -2.34897327e+01,
        7.82724075e+01, -2.08804970e+01,  5.05432968e+01,  5.36443558e+01,
       -1.78734245e+01, -1.49161148e+02, -8.89583206e+01,  4.40570183e+01,
        6.82772446e+01, -2.70865402e+01, -3.49038353e+01, -7.90106506e+01,
       -3.71459007e+01, -6.73876419e+01, -9.19265289e+01, -3.25276794e+01,
        3.20024948e+01,  1.28702957e+02, -1.61375565e+02,  5.87736626e+01,
        5.16838379e+01, -5.13497696e+01,  7.91688690e+01, -1.20859596e+02,
       -1.78251541e+02, -2.38155479e+01,  1.20154549e+02, -7.18701477e+01,
        1.78809719e+01, -

In [10]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)*100

98.34202775661485

# Hyperparameter tuning for XGBRegressor

***Hyperparameter tuning for XGBRegressor***

In [11]:
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor

model_name = XGBRegressor()

# Define the hyperparameter grid
param_grid = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.001, 0.01],
    'max_depth': [3, 4, 5, 6, 7, 8, 9, 10]
}

In [12]:
GridSearch = GridSearchCV(estimator=model_name, param_grid=param_grid, cv=5)
GridSearch

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, gamma=None,
                                    grow_policy=None, importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, m...
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None,
                                    random_state=None, ...),
             param_grid={'learning_rate': [0.001, 0.01],
                         'max_depth': [3, 4, 5, 6, 7, 8, 9, 10],
                         'n_estimators': [50, 100, 200]})

In [13]:
GridSearch.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, gamma=None,
                                    grow_policy=None, importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, m...
                                    max_cat_threshold=None,
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None,
                                    random_state=None, ...),
             param_grid={'learning_rate': [0.001, 0.01],
                         'max_depth': [3, 4, 5, 6, 7, 8, 9, 10],
                         'n_estimators': [50, 100, 200]})

In [15]:
GridSearch.best_params_

{'learning_rate': 0.01, 'max_depth': 6, 'n_estimators': 200}

In [16]:
best_model = GridSearch.best_estimator_

In [17]:
best_pred = best_model.predict(X_test)

In [19]:
best_pred

array([-2.85226369e+00, -1.25158806e+02,  1.10357876e+01, -1.69534164e+02,
        9.38620300e+01,  1.22863045e+02, -1.98829174e+01, -5.44785576e+01,
       -1.24425201e+01,  9.83133507e+00,  8.41504669e+00,  5.04174995e+01,
       -2.21291008e+01, -1.66808872e+01, -9.50838029e-01, -3.77870178e+01,
       -1.90834689e+00, -1.68974228e+02, -5.26478100e+00, -8.13811684e+00,
       -4.73449554e+01,  1.11147518e+01,  6.51968307e+01, -1.28760023e+01,
        7.06155701e+01, -1.28760023e+01,  4.45692940e+01,  5.12610054e+01,
       -4.99851227e+00, -1.27611938e+02, -8.28435364e+01,  4.39306450e+01,
        6.69764862e+01, -1.98829174e+01, -2.70894432e+01, -7.55192413e+01,
       -2.65138683e+01, -5.82122803e+01, -7.80928345e+01, -2.92135525e+01,
        2.80330296e+01,  1.11601868e+02, -1.32386459e+02,  5.10060272e+01,
        4.45692940e+01, -3.42969093e+01,  7.56091156e+01, -9.79635315e+01,
       -1.53802750e+02, -1.43576012e+01,  9.90730209e+01, -6.31348763e+01,
        1.57829189e+01, -